/* oxlint-disable */
// Generated by `pnpm build:html` (4da8d2d80d820812e7be9c984b94d53e)

export const html = `
<div id="stripe-form" style="max-width: 400px">
  <div id="payment-element" style="margin-bottom: 12px"></div>
  <button id="pay" type="button">Pay with card</button>
  <output id="status"></output>
</div>
  <script type="module">
    //#region node_modules/.pnpm/@stripe+stripe-js@8.9.0/node_modules/@stripe/stripe-js/dist/pure.mjs
    function _typeof(obj) {
    	"@babel/helpers - typeof";
    	if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") _typeof = function(obj) {
    		return typeof obj;
    	};
    	else _typeof = function(obj) {
    		return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
    	};
    	return _typeof(obj);
    }
    var RELEASE_TRAIN = "clover";
    var runtimeVersionToUrlVersion = function runtimeVersionToUrlVersion(version) {
    	return version === 3 ? "v3" : version;
    };
    var ORIGIN = "https://js.stripe.com";
    var STRIPE_JS_URL = "".concat(ORIGIN, "/").concat(RELEASE_TRAIN, "/stripe.js");
    var V3_URL_REGEX = /^https:\\/\\/js\\.stripe\\.com\\/v3\\/?(\\?.*)?$/;
    var STRIPE_JS_URL_REGEX = /^https:\\/\\/js\\.stripe\\.com\\/(v3|[a-z]+)\\/stripe\\.js(\\?.*)?$/;
    var EXISTING_SCRIPT_MESSAGE = "loadStripe.setLoadParameters was called but an existing Stripe.js script already exists in the document; existing script parameters will be used";
    var isStripeJSURL = function isStripeJSURL(url) {
    	return V3_URL_REGEX.test(url) || STRIPE_JS_URL_REGEX.test(url);
    };
    var findScript = function findScript() {
    	var scripts = document.querySelectorAll("script[src^=\\"".concat(ORIGIN, "\\"]"));
    	for (var i = 0; i < scripts.length; i++) {
    		var script = scripts[i];
    		if (!isStripeJSURL(script.src)) continue;
    		return script;
    	}
    	return null;
    };
    var injectScript = function injectScript(params) {
    	var queryString = params && !params.advancedFraudSignals ? "?advancedFraudSignals=false" : "";
    	var script = document.createElement("script");
    	script.src = "".concat(STRIPE_JS_URL).concat(queryString);
    	var headOrBody = document.head || document.body;
    	if (!headOrBody) throw new Error("Expected document.body not to be null. Stripe.js requires a <body> element.");
    	headOrBody.appendChild(script);
    	return script;
    };
    var registerWrapper = function registerWrapper(stripe, startTime) {
    	if (!stripe || !stripe._registerWrapper) return;
    	stripe._registerWrapper({
    		name: "stripe-js",
    		version: "8.9.0",
    		startTime
    	});
    };
    var stripePromise = null;
    var onErrorListener = null;
    var onLoadListener = null;
    var onError = function onError(reject) {
    	return function(cause) {
    		reject(new Error("Failed to load Stripe.js", { cause }));
    	};
    };
    var onLoad = function onLoad(resolve, reject) {
    	return function() {
    		if (window.Stripe) resolve(window.Stripe);
    		else reject(/* @__PURE__ */ new Error("Stripe.js not available"));
    	};
    };
    var loadScript = function loadScript(params) {
    	if (stripePromise !== null) return stripePromise;
    	stripePromise = new Promise(function(resolve, reject) {
    		if (typeof window === "undefined" || typeof document === "undefined") {
    			resolve(null);
    			return;
    		}
    		if (window.Stripe && params) console.warn(EXISTING_SCRIPT_MESSAGE);
    		if (window.Stripe) {
    			resolve(window.Stripe);
    			return;
    		}
    		try {
    			var script = findScript();
    			if (script && params) console.warn(EXISTING_SCRIPT_MESSAGE);
    			else if (!script) script = injectScript(params);
    			else if (script && onLoadListener !== null && onErrorListener !== null) {
    				var _script$parentNode;
    				script.removeEventListener("load", onLoadListener);
    				script.removeEventListener("error", onErrorListener);
    				(_script$parentNode = script.parentNode) === null || _script$parentNode === void 0 || _script$parentNode.removeChild(script);
    				script = injectScript(params);
    			}
    			onLoadListener = onLoad(resolve, reject);
    			onErrorListener = onError(reject);
    			script.addEventListener("load", onLoadListener);
    			script.addEventListener("error", onErrorListener);
    		} catch (error) {
    			reject(error);
    			return;
    		}
    	});
    	return stripePromise["catch"](function(error) {
    		stripePromise = null;
    		return Promise.reject(error);
    	});
    };
    var initStripe = function initStripe(maybeStripe, args, startTime) {
    	if (maybeStripe === null) return null;
    	var pk = args[0];
    	if (typeof pk !== "string") throw new Error("Expected publishable key to be of type string, got type ".concat(_typeof(pk), " instead."));
    	var isTestKey = pk.match(/^pk_test/);
    	var version = runtimeVersionToUrlVersion(maybeStripe.version);
    	var expectedVersion = RELEASE_TRAIN;
    	if (isTestKey && version !== expectedVersion) console.warn("Stripe.js@".concat(version, " was loaded on the page, but @stripe/stripe-js@").concat("8.9.0", " expected Stripe.js@").concat(expectedVersion, ". This may result in unexpected behavior. For more information, see https://docs.stripe.com/sdks/stripejs-versioning"));
    	var stripe = maybeStripe.apply(void 0, args);
    	registerWrapper(stripe, startTime);
    	return stripe;
    };
    var validateLoadParams = function validateLoadParams(params) {
    	var errorMessage = "invalid load parameters; expected object of shape\\n\\n    {advancedFraudSignals: boolean}\\n\\nbut received\\n\\n    ".concat(JSON.stringify(params), "\\n");
    	if (params === null || _typeof(params) !== "object") throw new Error(errorMessage);
    	if (Object.keys(params).length === 1 && typeof params.advancedFraudSignals === "boolean") return params;
    	throw new Error(errorMessage);
    };
    var loadParams;
    var loadStripeCalled = false;
    var loadStripe = function loadStripe() {
    	for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) args[_key] = arguments[_key];
    	loadStripeCalled = true;
    	var startTime = Date.now();
    	return loadScript(loadParams).then(function(maybeStripe) {
    		return initStripe(maybeStripe, args, startTime);
    	});
    };
    loadStripe.setLoadParameters = function(params) {
    	if (loadStripeCalled && loadParams) {
    		var validatedParams = validateLoadParams(params);
    		if (Object.keys(validatedParams).reduce(function(previousValue, currentValue) {
    			var _loadParams;
    			return previousValue && params[currentValue] === ((_loadParams = loadParams) === null || _loadParams === void 0 ? void 0 : _loadParams[currentValue]);
    		}, true)) return;
    	}
    	if (loadStripeCalled) throw new Error("You cannot change load parameters after calling loadStripe");
    	loadParams = validateLoadParams(params);
    };
    //#endregion
    //#region src/html/stripe/src/charge.ts
    var request = mppx.challenge.request;
    var stripe = await loadStripe(mppx.config.publishableKey);
    var isDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    var elements = stripe.elements({
    	mode: "payment",
    	amount: Number(request.amount),
    	currency: request.currency,
    	appearance: {
    		theme: isDark ? "night" : "stripe",
    		variables: { spacingUnit: "3px" }
    	},
    	paymentMethodTypes: ["card"],
    	paymentMethodCreation: "manual"
    });
    elements.create("payment", {
    	layout: "tabs",
    	fields: { billingDetails: { address: {
    		postalCode: "never",
    		country: "never"
    	} } },
    	wallets: { link: "never" }
    }).mount("#payment-element");
    var payBtn = document.getElementById("pay");
    var statusEl = document.getElementById("status");
    window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", (e) => {
    	elements.update({ appearance: { theme: e.matches ? "night" : "stripe" } });
    });
    payBtn.onclick = async () => {
    	payBtn.disabled = true;
    	const submitResult = await elements.submit();
    	if (submitResult.error) {
    		statusEl.textContent = submitResult.error.message;
    		statusEl.style.color = "red";
    		payBtn.disabled = false;
    		return;
    	}
    	const result = await stripe.createPaymentMethod({
    		elements,
    		params: { billing_details: { address: {
    			postal_code: "10001",
    			country: "US"
    		} } }
    	});
    	if (result.error) {
    		statusEl.textContent = result.error.message;
    		statusEl.style.color = "red";
    		payBtn.disabled = false;
    		return;
    	}
    	const res = await fetch("/api/create-spt", {
    		method: "POST",
    		headers: { "Content-Type": "application/json" },
    		body: JSON.stringify({
    			paymentMethod: result.paymentMethod.id,
    			amount: String(request.amount),
    			currency: request.currency,
    			expiresAt: Math.floor(Date.now() / 1e3) + 3600
    		})
    	});
    	if (!res.ok) {
    		statusEl.textContent = (await res.json()).error || "SPT creation failed";
    		statusEl.style.color = "red";
    		payBtn.disabled = false;
    		return;
    	}
    	const data = await res.json();
    	dispatchEvent(new CustomEvent("mppx:complete", { detail: mppx.serializeCredential({ spt: data.spt }) }));
    };
    //#endregion
  </script>
  `
