/* oxlint-disable */
// Generated by `pnpm build:html` (hash: 2d228199c7bf81af370abc61fcf46054)

export const content = `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!--mppx:head-->
  </head>
  <body>
    <!--mppx:data-->

    <header>
      <h1>Payment Required</h1>
    </header>
    <main>
      <section>
        <pre id="mppx-challenge"></pre>
      </section>
    </main>
    <!--mppx:script-->

    <!--mppx:method-->
  </body>
</html>`

export const script = `
  <script type="module">
    //#region src/html/page/src/page.ts
    var dataEl = document.getElementById("mppx-data");
    var { challenge, config } = JSON.parse(dataEl.textContent);
    function base64url(str) {
    	return btoa(str).replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");
    }
    function sortKeys(obj) {
    	const sorted = {};
    	Object.keys(obj).sort().forEach((k) => {
    		const v = obj[k];
    		sorted[k] = v && typeof v === "object" && !Array.isArray(v) ? sortKeys(v) : v;
    	});
    	return sorted;
    }
    window.mppx = Object.freeze({
    	challenge,
    	config,
    	serializeCredential(payload, source) {
    		const wire = {
    			challenge: Object.assign({}, mppx.challenge, { request: base64url(JSON.stringify(sortKeys(mppx.challenge.request))) }),
    			payload
    		};
    		if (source) wire.source = source;
    		return "Payment " + base64url(JSON.stringify(wire));
    	}
    });
    var challengeEl = document.getElementById("mppx-challenge");
    challengeEl.textContent = JSON.stringify(challenge, null, 2);
    if (challenge.description) {
    	const p = document.createElement("p");
    	p.textContent = challenge.description;
    	document.querySelector("header").appendChild(p);
    }
    function activateSw(reg) {
    	const sw = reg.installing || reg.waiting || reg.active;
    	return new Promise((resolve) => {
    		if (sw.state === "activated") return resolve();
    		sw.addEventListener("statechange", () => {
    			if (sw.state === "activated") resolve();
    		});
    	});
    }
    addEventListener("mppx:complete", ((e) => {
    	const statusEl = document.getElementById("status");
    	const authorization = e.detail;
    	if (statusEl) {
    		statusEl.textContent = "Verifying payment...";
    		statusEl.style.color = "";
    	}
    	navigator.serviceWorker.register("/__mppx_serviceWorker.js").then(activateSw).then(() => {
    		function sendAndReload() {
    			navigator.serviceWorker.controller.postMessage(authorization);
    			window.location.reload();
    		}
    		if (navigator.serviceWorker.controller) sendAndReload();
    		else navigator.serviceWorker.addEventListener("controllerchange", sendAndReload);
    	}).catch(() => {
    		fetch(window.location.href, { headers: { Authorization: authorization } }).then((res) => {
    			if (!res.ok) {
    				if (statusEl) {
    					statusEl.textContent = "Verification failed (" + res.status + ")";
    					statusEl.style.color = "red";
    				}
    				return;
    			}
    			return res.blob().then((blob) => {
    				window.location = URL.createObjectURL(blob);
    			});
    		}).catch((err) => {
    			if (statusEl) {
    				statusEl.textContent = err.message || "Request failed";
    				statusEl.style.color = "red";
    			}
    		});
    	});
    }));
    //#endregion
  </script>
  `

export const serviceWorker =
  'var e=null;self.addEventListener(`install`,()=>{self.skipWaiting()}),self.addEventListener(`activate`,e=>{e.waitUntil(self.clients.claim())}),self.addEventListener(`message`,t=>{e=t.data}),self.addEventListener(`fetch`,t=>{if(!e)return;let n=new Headers(t.request.headers);n.set(`Authorization`,e),e=null,t.respondWith(fetch(new Request(t.request,{headers:n})))});'
